// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1V41bKurbj6p49E6A0JwUd8HIYEcQ7S4',
    appId: '1:146239226655:web:0fc479584b5c222251662a',
    messagingSenderId: '146239226655',
    projectId: 'cybershield-518bd',
    authDomain: 'cybershield-518bd.firebaseapp.com',
    storageBucket: 'cybershield-518bd.firebasestorage.app',
    measurementId: 'G-5NJ53XWH22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74IfQPpHVCih0G-o8URieRfrF_6JT3Sg',
    appId: '1:146239226655:android:9d080c4ad17c7b2751662a',
    messagingSenderId: '146239226655',
    projectId: 'cybershield-518bd',
    storageBucket: 'cybershield-518bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGoewROm_ZMBaqDudww0Ld9k8WhMxK0zw',
    appId: '1:146239226655:ios:427a093d8215af0551662a',
    messagingSenderId: '146239226655',
    projectId: 'cybershield-518bd',
    storageBucket: 'cybershield-518bd.firebasestorage.app',
    iosBundleId: 'com.example.cybershield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGoewROm_ZMBaqDudww0Ld9k8WhMxK0zw',
    appId: '1:146239226655:ios:427a093d8215af0551662a',
    messagingSenderId: '146239226655',
    projectId: 'cybershield-518bd',
    storageBucket: 'cybershield-518bd.firebasestorage.app',
    iosBundleId: 'com.example.cybershield',
  );
}
